Repository antidot-framework/react-framework, pull requests merged in 2021-01, with the labels that each got.

#4 add missing pieces to run antidot with react php
  .gitignore
  README.md
  composer.json
  infection.log
  phpcs.xml.dist
  phpunit.xml.dist.bak
  psalm.xml
  src/Container/Config/ConfigProvider.php
  src/MiddlewarePipeline.php
  src/PromiseResponse.php
  src/ReactApplication.php
  src/ReactApplicationFactory.php
  test/Container/Config/ConfigProviderTest.php
  test/MiddlewarePipelineTest.php
  test/PromiseResponseTest.php
  test/ReactApplicationFactoryTest.php
  test/ReactApplicationTest.php
Labels: enhancement

#5 add readme
  README.md
  composer.json
Labels: documentation

#6 add version badge
  README.md
Labels: documentation

#7 fix config provider name in composer
  composer.json
Labels: bug, dependencies

#9 create psr factories
  src/Container/Config/ConfigProvider.php
  src/LoopFactory.php
  src/ReactApplication.php
  src/ReactApplicationFactory.php
  src/ServerFactory.php
  src/SocketFactory.php
  test/Container/Config/ConfigProviderTest.php
  test/LoopFactoryTest.php
  test/ReactApplicationFactoryTest.php
  test/ReactApplicationTest.php
  test/ServerFactoryTest.php
  test/SocketFactoryTest.php
Labels: enhancement

#10 fix resolve handler on react server
  src/ServerFactory.php
Labels: bug

#15 add github actions
  .github/workflows/coding-standards.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
Labels: dependencies

#17 bump antidot version to 0.2.0
  composer.json
Labels: dependencies

#16 Resolving issue#30 for antidot-framework
  src/ReactApplication.php
Labels: enhancement

#18 use new middleware queue
  src/MiddlewarePipeline.php
  src/ReactApplication.php
Labels: bug, dependencies

#19 update readme
  README.md
Labels: documentation
